# Generated by Django 4.1.4 on 2022-12-12 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0006_movieorder_movie_orders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="owner",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="movieorder",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movie_order",
                to="movies.movie",
            ),
        ),
        migrations.AlterField(
            model_name="movieorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_movie_order",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
